CREATE TABLE `booking_offers` (
  `offer_id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `original_booking_id` CHAR(36) NOT NULL,
  `alternative_apartment_id` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `created_by_staff_id` CHAR(36) NULL,
  `original_price` DECIMAL(12,2) NOT NULL,
  `alternative_price` DECIMAL(12,2) NOT NULL,
  `price_difference` DECIMAL(12,2) NOT NULL,
  `status` ENUM('pending','accepted','rejected','expired','cancelled') NOT NULL DEFAULT 'pending',
  `reason` VARCHAR(100) NULL,
  `expires_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `responded_at` TIMESTAMP NULL,
  `tenant_response_notes` TEXT NULL,
  PRIMARY KEY (`offer_id`),
  KEY `idx_original_booking` (`original_booking_id`),
  KEY `idx_alternative_apartment` (`alternative_apartment_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_status` (`status`),
  KEY `idx_expires_at` (`expires_at`),
  CONSTRAINT `booking_offers_ibfk_1` FOREIGN KEY (`original_booking_id`) REFERENCES `bookings` (`booking_id`),
  CONSTRAINT `booking_offers_ibfk_2` FOREIGN KEY (`alternative_apartment_id`) REFERENCES `apartments` (`apartment_id`),
  CONSTRAINT `booking_offers_ibfk_3` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`),
  CONSTRAINT `booking_offers_ibfk_4` FOREIGN KEY (`created_by_staff_id`) REFERENCES `users` (`user_id`) ON DELETE SET NULL
);
